apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NODE_ENV: "production"
  PRODUCT_API_URL: "http://product-service:5002"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 encoded string for a dummy secret key
  JWT_SECRET: bXktc3VwZXItc2VjcmV0LWtleS0xMjM0NQ==